const ADD_TO_LIKE = 'ADD_TO_LIKE';
const REMOVE_FROM_LIKE = 'REMOVE_FROM_LIKE';
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export {
    ADD_TO_CART,
    REMOVE_FROM_CART,
    ADD_TO_LIKE,
    REMOVE_FROM_LIKE
}